settings:
  title: 'STATUS PIRATE SITE'
  url: 'https://status.piratesite.net/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Wszystkie systemy sprawne'
  notAllmonitorsOperational: 'Nie wszystkie systemy są sprawne'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Nieczynne'
  monitorLabelNoData: 'Brak danych'
  dayInHistogramNoData: 'Brak danych'
  dayInHistogramOperational: 'Wszystko dobrze'
  dayInHistogramNotOperational: ' zdarzenie(-a)' # xx incident(s) recorded

monitors:
  - id: piratesite-net # unique identifier
    name: piratesite.net
    description: 'Status działania serwera strony' # default=empty
    url: 'https://piratesite.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

